2019-07-23 15:27:59,480 ERROR 31944 [-/127.0.0.1/-/1ms GET /] nodejs.ER_ACCESS_DENIED_ERRORError: ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'localhost' (using password: NO)
    at Handshake.Sequence._packetToError (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/sequences/Handshake.js:123:18)
    at Protocol._parsePacket (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/Connection.js:525:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    --------------------
    at Protocol._enqueue (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/Connection.js:119:18)
    at Pool.getConnection (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/Pool.js:48:16)
    at /Users/mac/Desktop/blog-web/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/mac/Desktop/blog-web/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as getConnection] (/Users/mac/Desktop/blog-web/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at Pool.query (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/Pool.js:202:8)
    at /Users/mac/Desktop/blog-web/node_modules/ali-rds/node_modules/pify/index.js:29:7
    sql: select now() as currentTime;
code: "ER_ACCESS_DENIED_ERROR"
errno: 1045
sqlMessage: "Access denied for user 'root'@'localhost' (using password: NO)"
sqlState: "28000"
fatal: true
name: "ER_ACCESS_DENIED_ERRORError"
pid: 31944
hostname: MacBook-Pro-3.local

2019-07-23 15:28:03,787 ERROR 31953 [-/127.0.0.1/-/1ms GET /] nodejs.ER_ACCESS_DENIED_ERRORError: ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'localhost' (using password: NO)
    at Handshake.Sequence._packetToError (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/sequences/Handshake.js:123:18)
    at Protocol._parsePacket (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/Connection.js:525:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    --------------------
    at Protocol._enqueue (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/Connection.js:119:18)
    at Pool.getConnection (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/Pool.js:48:16)
    at /Users/mac/Desktop/blog-web/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/mac/Desktop/blog-web/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as getConnection] (/Users/mac/Desktop/blog-web/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at Pool.query (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/Pool.js:202:8)
    at /Users/mac/Desktop/blog-web/node_modules/ali-rds/node_modules/pify/index.js:29:7
    sql: select now() as currentTime;
code: "ER_ACCESS_DENIED_ERROR"
errno: 1045
sqlMessage: "Access denied for user 'root'@'localhost' (using password: NO)"
sqlState: "28000"
fatal: true
name: "ER_ACCESS_DENIED_ERRORError"
pid: 31953
hostname: MacBook-Pro-3.local

2019-07-23 15:28:08,313 ERROR 31956 [-/127.0.0.1/-/1ms GET /] nodejs.ER_ACCESS_DENIED_ERRORError: ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'localhost' (using password: NO)
    at Handshake.Sequence._packetToError (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/sequences/Handshake.js:123:18)
    at Protocol._parsePacket (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/Connection.js:525:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    --------------------
    at Protocol._enqueue (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/Connection.js:119:18)
    at Pool.getConnection (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/Pool.js:48:16)
    at /Users/mac/Desktop/blog-web/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/mac/Desktop/blog-web/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as getConnection] (/Users/mac/Desktop/blog-web/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at Pool.query (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/Pool.js:202:8)
    at /Users/mac/Desktop/blog-web/node_modules/ali-rds/node_modules/pify/index.js:29:7
    sql: select now() as currentTime;
code: "ER_ACCESS_DENIED_ERROR"
errno: 1045
sqlMessage: "Access denied for user 'root'@'localhost' (using password: NO)"
sqlState: "28000"
fatal: true
name: "ER_ACCESS_DENIED_ERRORError"
pid: 31956
hostname: MacBook-Pro-3.local

2019-07-23 15:28:09,532 ERROR 31958 [-/127.0.0.1/-/0ms GET /] nodejs.ER_ACCESS_DENIED_ERRORError: ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'localhost' (using password: NO)
    at Handshake.Sequence._packetToError (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/sequences/Handshake.js:123:18)
    at Protocol._parsePacket (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/Connection.js:525:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    --------------------
    at Protocol._enqueue (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/Connection.js:119:18)
    at Pool.getConnection (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/Pool.js:48:16)
    at /Users/mac/Desktop/blog-web/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/mac/Desktop/blog-web/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as getConnection] (/Users/mac/Desktop/blog-web/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at Pool.query (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/Pool.js:202:8)
    at /Users/mac/Desktop/blog-web/node_modules/ali-rds/node_modules/pify/index.js:29:7
    sql: select now() as currentTime;
code: "ER_ACCESS_DENIED_ERROR"
errno: 1045
sqlMessage: "Access denied for user 'root'@'localhost' (using password: NO)"
sqlState: "28000"
fatal: true
name: "ER_ACCESS_DENIED_ERRORError"
pid: 31958
hostname: MacBook-Pro-3.local

2019-07-23 15:28:18,480 ERROR 31960 [-/127.0.0.1/-/0ms GET /] nodejs.ER_ACCESS_DENIED_ERRORError: ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'localhost' (using password: NO)
    at Handshake.Sequence._packetToError (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/sequences/Handshake.js:123:18)
    at Protocol._parsePacket (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/Connection.js:525:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    --------------------
    at Protocol._enqueue (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/Connection.js:119:18)
    at Pool.getConnection (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/Pool.js:48:16)
    at /Users/mac/Desktop/blog-web/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/mac/Desktop/blog-web/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as getConnection] (/Users/mac/Desktop/blog-web/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at Pool.query (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/Pool.js:202:8)
    at /Users/mac/Desktop/blog-web/node_modules/ali-rds/node_modules/pify/index.js:29:7
    sql: select now() as currentTime;
code: "ER_ACCESS_DENIED_ERROR"
errno: 1045
sqlMessage: "Access denied for user 'root'@'localhost' (using password: NO)"
sqlState: "28000"
fatal: true
name: "ER_ACCESS_DENIED_ERRORError"
pid: 31960
hostname: MacBook-Pro-3.local

2019-07-23 15:28:34,961 ERROR 31961 [-/127.0.0.1/-/1ms GET /] nodejs.ER_BAD_DB_ERRORError: ER_BAD_DB_ERROR: Unknown database 'operation_policy_clamp_00'
    at Handshake.Sequence._packetToError (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/sequences/Handshake.js:123:18)
    at Protocol._parsePacket (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/Connection.js:525:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    --------------------
    at Protocol._enqueue (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/Connection.js:119:18)
    at Pool.getConnection (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/Pool.js:48:16)
    at /Users/mac/Desktop/blog-web/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/mac/Desktop/blog-web/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as getConnection] (/Users/mac/Desktop/blog-web/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at Pool.query (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/Pool.js:202:8)
    at /Users/mac/Desktop/blog-web/node_modules/ali-rds/node_modules/pify/index.js:29:7
    sql: select now() as currentTime;
code: "ER_BAD_DB_ERROR"
errno: 1049
sqlMessage: "Unknown database 'operation_policy_clamp_00'"
sqlState: "42000"
fatal: true
name: "ER_BAD_DB_ERRORError"
pid: 31961
hostname: MacBook-Pro-3.local

2019-07-23 15:28:36,370 ERROR 31963 [-/127.0.0.1/-/0ms GET /] nodejs.ER_BAD_DB_ERRORError: ER_BAD_DB_ERROR: Unknown database 'operation_policy_clamp_00'
    at Handshake.Sequence._packetToError (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/sequences/Handshake.js:123:18)
    at Protocol._parsePacket (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/Connection.js:525:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    --------------------
    at Protocol._enqueue (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/Connection.js:119:18)
    at Pool.getConnection (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/Pool.js:48:16)
    at /Users/mac/Desktop/blog-web/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/mac/Desktop/blog-web/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as getConnection] (/Users/mac/Desktop/blog-web/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at Pool.query (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/Pool.js:202:8)
    at /Users/mac/Desktop/blog-web/node_modules/ali-rds/node_modules/pify/index.js:29:7
    sql: select now() as currentTime;
code: "ER_BAD_DB_ERROR"
errno: 1049
sqlMessage: "Unknown database 'operation_policy_clamp_00'"
sqlState: "42000"
fatal: true
name: "ER_BAD_DB_ERRORError"
pid: 31963
hostname: MacBook-Pro-3.local

2019-07-23 15:28:45,494 ERROR 31964 [-/127.0.0.1/-/0ms GET /] nodejs.ER_BAD_DB_ERRORError: ER_BAD_DB_ERROR: Unknown database 'blog-web'
    at Handshake.Sequence._packetToError (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/sequences/Handshake.js:123:18)
    at Protocol._parsePacket (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/Connection.js:525:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    --------------------
    at Protocol._enqueue (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at PoolConnection.connect (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/Connection.js:119:18)
    at Pool.getConnection (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/Pool.js:48:16)
    at /Users/mac/Desktop/blog-web/node_modules/ali-rds/node_modules/pify/index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (/Users/mac/Desktop/blog-web/node_modules/ali-rds/node_modules/pify/index.js:12:10)
    at Pool.ret [as getConnection] (/Users/mac/Desktop/blog-web/node_modules/ali-rds/node_modules/pify/index.js:56:34)
    at Pool.query (/Users/mac/Desktop/blog-web/node_modules/mysql/lib/Pool.js:202:8)
    at /Users/mac/Desktop/blog-web/node_modules/ali-rds/node_modules/pify/index.js:29:7
    sql: select now() as currentTime;
code: "ER_BAD_DB_ERROR"
errno: 1049
sqlMessage: "Unknown database 'blog-web'"
sqlState: "42000"
fatal: true
name: "ER_BAD_DB_ERRORError"
pid: 31964
hostname: MacBook-Pro-3.local

2019-07-23 19:29:58,764 ERROR 32120 nodejs.ClusterClientNoResponseError: client no response in 2301281ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/mac/Desktop/blog-web/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
name: "ClusterClientNoResponseError"
pid: 32120
hostname: MacBook-Pro-3.local

2019-07-23 20:35:46,101 ERROR 32120 nodejs.ClusterClientNoResponseError: client no response in 3907289ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/mac/Desktop/blog-web/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
name: "ClusterClientNoResponseError"
pid: 32120
hostname: MacBook-Pro-3.local

2019-07-23 23:57:28,389 ERROR 32120 nodejs.ClusterClientNoResponseError: client no response in 12082284ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/mac/Desktop/blog-web/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
name: "ClusterClientNoResponseError"
pid: 32120
hostname: MacBook-Pro-3.local

2019-07-24 09:51:36,977 ERROR 32120 nodejs.ClusterClientNoResponseError: client no response in 35608581ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/mac/Desktop/blog-web/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
name: "ClusterClientNoResponseError"
pid: 32120
hostname: MacBook-Pro-3.local

2019-07-24 10:00:00,233 ERROR 32120 nodejs.ClusterClientNoResponseError: client no response in 463250ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (/Users/mac/Desktop/blog-web/node_modules/cluster-client/lib/leader.js:77:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
name: "ClusterClientNoResponseError"
pid: 32120
hostname: MacBook-Pro-3.local

